### ISSUE TITLE
create package: time

### ISSUE THREAD

**Issue by bosley** [sauros/sauros#32]
Need a package that will allow getting time stamps and calculating time deltas. 
The ability to change units of time easily is required

Idea example:
```
[var start[time.stamp]]
; Some time intensive operation
[var end[time.stamp]]

[var delta [- end start]]

[putln [time.to_seconds delta]]

```
The resulting package doesn't need to look exactly like the example - Its just an idea

**Comment by ryuusama09** [comment]
hey @bosley  , so if you are asking for suggestion then you can use the chrono library used in c++ This will help you maintain language similarity

**Comment by bosley** [comment]
Thanks for the suggestion, I agree that chrono should be used on the c++ side of this package. I've posted these issues to keep track of todo work and listed easy ones if someone wants to help - this task involves creating a `time` package that would be listed  [here](https://github.com/bosley/sauros/tree/main/pkgs) with a c++ backend.

**Comment by bosley** [comment]
https://github.com/bosley/sauros/pull/43
